### ISSUE TITLE
Mongo gem version required must be less than 2.0 (working with 1.12.5)

### ISSUE THREAD

**Issue by nannal** [gehrhorn/nessus-analyzer#3]
Errors presented: 
```
root@debian:~/nessus-analyzer# ./nessus-analyzer.rb -f report.nessus -d production
uninitialized constant MongoClient
./nessus-analyzer.rb:218:in `ensure in make_mongo_doc': undefined method `close' for nil:NilClass (NoMethodError)
Did you mean?  clone
	from ./nessus-analyzer.rb:218:in `make_mongo_doc'
	from ./nessus-analyzer.rb:237:in `block in process_nessus_file'
	from /usr/lib/ruby/2.3.0/gems/ruby-nessus-1.2.0/lib/nessus/parse.rb:32:in `initialize'
	from ./nessus-analyzer.rb:226:in `new'
	from ./nessus-analyzer.rb:226:in `process_nessus_file'
	from ./nessus-analyzer.rb:291:in `<main>'
```

Resolve with: 
`gem install mongo -v '< 2'`

**Comment by gehrhorn** [comment]
Thanks @nannal. This looks like a pretty easy fix in the Gemfile. Do you want to send me a pull request?
